spring:
    profiles:
        active: dev
---
server:
    port: 8081
spring:
    profiles: dev
    application: 
        name: microservice-config-dev
eureka:
    client:
        defaultZone: http://eureka7001.com:7001/eureka
---
server:
    port: 8082
spring:
    profiles: test
    application: 
        name: microservice-config-test
eureka:
    client:
        defaultZone: http://eureka7002.com:7002/eureka
